### ISSUE TITLE
Kong Pods Load not balanced (02. Mar 2021)

### ISSUE THREAD

**Issue by cadiegoc** [giantswarm/kong-app#103]
Hi GS,

One team did some Load tests using Kong in Schn01 (China Kubernetes cluster) and saw that some pods were having way more load than others, resulting in instability of response time. Please check the following PDF with all info from our ticket: 
[APIS-61 Kong Pods load not balanced in Scn01.pdf](https://github.com/giantswarm/kong-app/files/6067635/APIS-61.Kong.Pods.load.not.balanced.in.Scn01.pdf)

Thank you for your time.

**Comment by othylmann** [comment]
@giantswarm/team-halo can you please check urgently as China is doing some tests. Thx.

**Comment by ubergesundheit** [comment]
Hello @cadiegoc,

from looking at your linked PDF I cannot really see what could have caused the uneven spread of load.

For the first chart, are you sure the pods all a have the same age? In the sense of "older pods served more requests since they're around longer".

Maybe @yasn77 has deeper insight.

**Comment by yasn77** [comment]
It's difficult to exactly say as the pods no longer exist.... However the first place I would (and did) look is to see if traffic from the NLB is unbalanced. As one potential issue could be related to session affinity... However the NLB don't have any sticky or session affinity set up. Unfortunately i couldn't find any metrics that showed what nodes in the target group are being used, but I did find that active connections primarily existed on an NLB in a single AZ:

![Screenshot from 2021-03-02 23-26-10](https://user-images.githubusercontent.com/2234002/109728807-d0a60800-7bae-11eb-8c79-b960220e4887.jpg)

From that you can see the majority of connections are on NLB in AZ `cn-north-1a`, so the logical conclusion would be that the pods in the graph you posted existed in that AZ.

My next step suggestion would be to validate how the perf test is configured... For example, is it caching DNS of the NLB? Picking the response in AZ B then only sending there? Is the Perf test hitting a CDN? Is the CDN configured to balance the traffic?

To be honest, I think this as far as we can go... I can't conclusively say it is because of what i described, but I would suggest that the graph from AWS would say it is.

**Comment by maxyang2008** [comment]
Hi Team,

1. The configured domain doesn't have CDN attached
2.  we are using jmeter for perf test and no DNS cache is configured.

My question is that:
1. How NLB distributed load to backends? 
2. Can NLB access log be used to calculate how many requests are distributed to each backend service?

Thanks.

**Comment by yasn77** [comment]
> 2. we are using jmeter for perf test and no DNS cache is configured.
> 

JMeter under the underhood is using Java, which from experience can be an issue with its own DNS caching mechanism. JMeter can be configured so that each thread makes it's own request (i.e cache is cleared for each thread/iteration). This site is useful in explaining how to configure https://www.blazemeter.com/blog/dns-cache-manager-right-way-test-load-balanced-apps

> My question is that:
> 
> 1. How NLB distributed load to backends?

>For TCP traffic, the load balancer selects a target using a flow hash algorithm based on the protocol, source IP address, source port, destination IP address, destination port, and TCP sequence number. The TCP connections from a client have different source ports and sequence numbers, and can be routed to different targets. Each individual TCP connection is routed to a single target for the life of the connection.

(From https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html)

> 2. Can NLB access log be used to calculate how many requests are distributed to each backend service?

I am not sure if logs are enabled, the API team would be able to verify that

**Comment by maxyang2008** [comment]
Hi Team,
after running jmeter with DNS cache disabled, traffic to each Kong pods still not balanced.
Please see the below screenshot.

![image](https://user-images.githubusercontent.com/2622779/109824679-0234d700-7c74-11eb-9348-fbcd5dc6a7ee.png)

**Comment by yasn77** [comment]
@maxyang2008 Thanks for the screenshot.... The balancing looks a lot better than the initial screenshot 👍🏽 

TBH if there is no increased error rate or latency then I am not sure there is much more that can be done. We are not likely to see absolute equal balancing. As described by AWS documentation, there is a chance that requests will go to the same target.

@narsipra @rathonit01 It would be good to get the teams input. Thanks

**Comment by maxyang2008** [comment]
Hi @yasn77 ,

The difference between the highest and lowest calls is around 70,000, which is still a large difference.
Now there are only 12 pods, I am not sure how will the graph looks when having more kong pods.
But let me watch it for more time to see if there will be something.

I still have 2 question:
1. For every http request by client program, which pods it will goes to is determined by NLB, is that right?
2. Is there somewhere I can see the capacity limit of NLB? how much traffic can NLB handle?

Thanks.

**Comment by yasn77** [comment]
> 1. For every http request by client program, which pods it will goes to is determined by NLB, is that right?

Yes, the traffic is terminating at the AWS NLB and the decision as to which backend Kong to send the traffic is decided by the AWS NLB Load Balancing algorithm 

> 2. Is there somewhere I can see the capacity limit of NLB? how much traffic can NLB handle?

Cloudwatch metrics can give a good indication of its usage.

But as I mentioned, I am not sure if there is much need for further investigation. If you are not seeing increased latency or increased error rates then I would say that things are behaving in an OK manner. You are not likely going to see a totally even distribution. Also, it is worth noting that the Kong service can use Horizontal Pod Autoscaling *and* some are running on spot instances, so the graphs can skewed as pods come and go (so traffic will favour one pod more than another since it's around longer)

**Comment by maxyang2008** [comment]
Hi @yasn77 ,
can we put this on hold?
Our perf test will continue, and let's see if I can find more to verify.

Thanks.

**Comment by othylmann** [comment]
I am closing this due to having found out that it is all within boundaries.
